In [1]:
import pandas
import datetime
import numpy
import scipy.optimize
import seaborn as sns
import matplotlib.pyplot as plt
import os
import time
import bs4
import urllib
from matplotlib.colors import ListedColormap
from matplotlib.colors import Normalize
from matplotlib import ticker
%matplotlib inline
from matplotlib import rcParams

In [2]:
# setup some cutoff values we'll use in the analysis
velCutoffUpper = 2000.
velCutoffLower = 0.
numPointsCutoffMLTMLAT = 250
mlatCutOffUpper = 70.

In [3]:
velGmagDF = pandas.read_csv("../data/processed-vels-geomag.txt", sep=' ',\
                            parse_dates=["date", "dst_date"], infer_datetime_format=True)
velGmagDF = velGmagDF.drop('Unnamed: 0', axis=1)
# Filter out some values where number of datapoints are pretty low.
countDF = velGmagDF.groupby([ "normMLT", "MLAT" ]).size().reset_index()
countDF.columns = [ "normMLT", "MLAT", "count" ]
# Choose only columns which have atleast 100 points
countDF = countDF[ countDF["count"] >= numPointsCutoffMLTMLAT ].reset_index(drop=True)
# Merge with velsDataDF to filter out unwanted values
velGmagDF = pandas.merge( velGmagDF, countDF,\
                          on=["normMLT", "MLAT"], how='inner' )
# Discard unwanted values
# We'll only consider those velocities 
# which lie between 0 and 2500 m/s
# and located below 70 MLAT
velGmagDF = velGmagDF[ (velGmagDF["vSaps"] > velCutoffLower) \
                        & (velGmagDF["vSaps"] < velCutoffUpper)\
                       ].reset_index(drop=True)
velGmagDF = velGmagDF[ velGmagDF["MLAT"] < mlatCutOffUpper ].reset_index(drop=True)
velGmagDF.head()

,normMLT,MLAT,vSaps,azim,vMagnErr,azimErr,dtStr,tmStr,date,hour,dst_date,dst_index,dst_bin,AE,AL,AO,AU,minute,count
0,-4.0,60.5,634.32,-10.10,7.19,21.54,20130316,500,2013-03-16 05:00:00,5,2013-03-16 05:00:00,-19.0,"(-25, -10]",731,-575,-210,156,0,2677
1,-4.0,60.5,609.64,-10.92,3.58,9.73,20130316,502,2013-03-16 05:02:00,5,2013-03-16 05:00:00,-19.0,"(-25, -10]",651,-524,-199,127,2,2677
2,-4.0,60.5,613.71,-12.20,4.15,8.27,20130316,504,2013-03-16 05:04:00,5,2013-03-16 05:00:00,-19.0,"(-25, -10]",586,-470,-177,116,4,2677
3,-4.0,60.5,778.50,-16.19,3.80,4.90,20130316,506,2013-03-16 05:06:00,5,2013-03-16 05:00:00,-19.0,"(-25, -10]",562,-418,-137,144,6,2677
4,-4.0,60.5,578.11,-15.40,7.43,12.92,20130316,508,2013-03-16 05:08:00,5,2013-03-16 05:00:00,-19.0,"(-25, -10]",569,-450,-166,119,8,2677

In [4]:
# Lets get max, min and std.dev across each MLT for each time
# this way we'll try to isolate SAID channels
maxVelDF = velGmagDF.groupby( ["date", "normMLT"] )[ "vSaps", "azim", "MLAT" ].max().reset_index()
maxVelDF.rename(columns={'vSaps': 'vSapsMax','azim': 'azimMax','MLAT': 'mlatMax'}, inplace=True)

minVelDF = velGmagDF.groupby( ["date", "normMLT"] )[ "vSaps", "azim", "MLAT" ].min().reset_index()
minVelDF.rename(columns={'vSaps': 'vSapsMin','azim': 'azimMin','MLAT': 'mlatMin'}, inplace=True)

medianVelDF = velGmagDF.groupby( ["date", "normMLT"] )[ "vSaps", "azim", "MLAT" ].median().reset_index()
medianVelDF.rename(columns={'vSaps': 'vSapsMedian','azim': 'azimMedian','MLAT': 'mlatMedian'}, inplace=True)

stdVelDF = velGmagDF.groupby( ["date", "normMLT"] )[ "vSaps", "azim", "MLAT" ].std().reset_index()
stdVelDF.rename(columns={'vSaps': 'vSapsStd','azim': 'azimStd','MLAT': 'mlatStd'}, inplace=True)

sapsDF = maxVelDF.merge( minVelDF, on=["date","normMLT"] ).\
                merge( medianVelDF, on=["date","normMLT"] ).\
                merge( stdVelDF, on=["date","normMLT"] )

sapsDF.head()

,date,normMLT,vSapsMax,azimMax,mlatMax,vSapsMin,azimMin,mlatMin,vSapsMedian,azimMedian,mlatMedian,vSapsStd,azimStd,mlatStd
0,2011-02-05 02:30:00,-5.0,704.08,-7.26,63.5,227.38,-9.81,59.0,580.705,-8.355,61.25,146.690838,0.949695,1.513825
1,2011-02-05 02:30:00,-4.0,704.08,-7.26,63.0,543.42,-9.81,59.5,606.970,-7.960,61.25,58.850929,0.951502,1.224745
2,2011-02-05 02:30:00,-3.0,635.56,-5.38,63.0,531.04,-7.26,59.5,612.110,-6.355,61.25,36.448429,0.667014,1.224745
3,2011-02-05 02:32:00,-5.0,615.93,-4.76,63.5,213.15,-8.53,59.0,555.810,-7.260,61.25,161.409982,1.014580,1.513825
4,2011-02-05 02:32:00,-4.0,615.93,-4.76,63.0,498.32,-8.53,59.5,586.435,-6.955,61.25,45.000333,1.301498,1.224745

In [5]:
# We'll set up a few criteria for isolating SAID channels
# 1) SAID datetimes have max velocities greater than 1000 m/s
sapsDF = sapsDF[ sapsDF["vSapsMax"] >= 1000. ].reset_index(drop=True)
# 2) Latitude difference (max-min) is greater than 2 degrees
sapsDF = sapsDF[ (sapsDF["mlatMax"] - sapsDF["mlatMin"]) > 2. ].reset_index(drop=True)
# 3) Stdev in Velocities should be greater than 250 m/s
sapsDF = sapsDF[ sapsDF["vSapsStd"] > 250. ].reset_index(drop=True)
sapsDF.head()

,date,normMLT,vSapsMax,azimMax,mlatMax,vSapsMin,azimMin,mlatMin,vSapsMedian,azimMedian,mlatMedian,vSapsStd,azimStd,mlatStd
0,2011-03-02 02:26:00,-2.0,1923.54,-5.61,62.5,928.08,-12.97,59.0,1312.330,-7.700,60.50,341.606848,3.153589,1.205148
1,2011-03-02 02:28:00,-2.0,1594.03,-5.81,61.5,877.95,-15.31,59.0,1259.895,-8.625,60.25,292.061807,3.848966,0.935414
2,2011-03-12 00:50:00,-5.0,1179.78,4.11,61.0,188.28,2.68,58.5,942.670,3.205,59.75,346.923597,0.727225,0.935414
3,2011-03-12 00:50:00,-4.0,1128.93,4.25,61.0,489.12,2.68,58.0,1004.240,4.110,59.50,263.770741,0.803818,1.080123
4,2011-03-12 00:52:00,-4.0,1185.96,4.02,60.5,465.18,3.73,58.0,1024.165,3.735,59.25,250.021061,0.116862,0.935414

In [6]:
# Now merge the sapsDF dates with velGmagDF
sapsDF = pandas.merge( sapsDF, velGmagDF, on=["date", "normMLT"] )
selCols = [ "date", "normMLT", "vSaps", "vSapsMax", "vSapsMin", "vSapsMedian"]
sapsDF[selCols].head()

,date,normMLT_x,vSapsMax,azimMax,mlatMax,vSapsMin,azimMin,mlatMin,vSapsMedian,azimMedian,...,hour,dst_date,dst_index,dst_bin,AE,AL,AO,AU,minute,count
0,2011-03-02 02:26:00,-2.0,1923.54,-5.61,62.5,928.08,-12.97,59.0,1312.33,-7.7,...,2,2011-03-02 02:00:00,-45.0,"(-50, -25]",251,-135,-10,116,26,2677
1,2011-03-02 02:26:00,-2.0,1923.54,-5.61,62.5,928.08,-12.97,59.0,1312.33,-7.7,...,2,2011-03-02 02:00:00,-45.0,"(-50, -25]",251,-135,-10,116,26,3332
2,2011-03-02 02:26:00,-2.0,1923.54,-5.61,62.5,928.08,-12.97,59.0,1312.33,-7.7,...,2,2011-03-02 02:00:00,-45.0,"(-50, -25]",251,-135,-10,116,26,3479
3,2011-03-02 02:26:00,-2.0,1923.54,-5.61,62.5,928.08,-12.97,59.0,1312.33,-7.7,...,2,2011-03-02 02:00:00,-45.0,"(-50, -25]",251,-135,-10,116,26,2500
4,2011-03-02 02:26:00,-2.0,1923.54,-5.61,62.5,928.08,-12.97,59.0,1312.33,-7.7,...,2,2011-03-02 02:00:00,-45.0,"(-50, -25]",251,-135,-10,116,26,3115