In [1]:
import pandas
import datetime
import numpy
from scipy.optimize import curve_fit
import seaborn as sns
import matplotlib.pyplot as plt
import os
%matplotlib inline

In [2]:
# file with velocities
rawVelFileName = "../data/test-vels-north.txt"
# need to format the file appropritely, before we can read it
outFormattedFile = "../data/formatted-vels.txt"
os.system( 'cat ' + rawVelFileName + ' | tr -s " " > ' + outFormattedFile )
inpColNames = [ "dateStr", "timeStr", "beam", "range", \
          "azim", "Vlos", "MLAT", "MLON", "MLT", "radId", \
          "radCode"]
velsDataDF = pandas.read_csv(outFormattedFile, sep=' ',\
                             header=None, names=inpColNames)
# add a datetime col
velsDataDF["date"] = pandas.to_datetime( \
                        velsDataDF['dateStr'].astype(str) + "-" +\
                        velsDataDF['timeStr'].astype(str), format='%Y%m%d-%H%M')
velsDataDF.head()

/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py:1159: DtypeWarning: Columns (6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  data = self._reader.read(nrows)

,dateStr,timeStr,beam,range,azim,Vlos,MLAT,MLON,MLT,radId,radCode
0,20110409,600,0,26,-60.95,-2.2716,53.2044,-21.8611,23.6993,33,bks
1,20110409,600,0,27,-60.95,-5.1056,53.3065,-22.5771,23.6515,33,bks
2,20110409,600,0,28,-60.95,-5.1056,53.4035,-23.2954,23.6036,33,bks
3,20110409,600,0,29,-60.95,-4.5666,53.4954,-24.0159,23.5556,33,bks
4,20110409,600,0,30,-60.95,-3.6944,53.5823,-24.7384,23.5074,33,bks

,dateStr,timeStr,beam,range,azim,Vlos,MLAT,MLON,MLT,radId,radCode,date
0,20110409,600,0,26,-60.95,-2.2716,53.2044,-21.8611,23.6993,33,bks,2011-04-09 06:00:00
1,20110409,600,0,27,-60.95,-5.1056,53.3065,-22.5771,23.6515,33,bks,2011-04-09 06:00:00
2,20110409,600,0,28,-60.95,-5.1056,53.4035,-23.2954,23.6036,33,bks,2011-04-09 06:00:00
3,20110409,600,0,29,-60.95,-4.5666,53.4954,-24.0159,23.5556,33,bks,2011-04-09 06:00:00
4,20110409,600,0,30,-60.95,-3.6944,53.5823,-24.7384,23.5074,33,bks,2011-04-09 06:00:00